### ISSUE TITLE
Not sure if this is the right place, but your website is not working.

### ISSUE THREAD

**Issue by Bendak** [ValentinVoigt/stormworks-sign-generator-web#1]
Whenever i submit am image to the website, it gives an error:
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

So it does not generate the save game file.

The image is a simple Brasil flag (attached) trying to generate a 4x3 block size. But any size i attempt gives same error.
![Brasil](https://user-images.githubusercontent.com/13473098/59986220-308f9180-960c-11e9-9a4a-5cf7a267dfdc.png)

**Comment by ValentinVoigt** [comment]
Thanks for the info! The server's disk was full. It is working again.
